### ISSUE TITLE
Support for Sails v0.11?

### ISSUE THREAD

**Issue by benwilhelm** [building5/sails-db-migrate#18]
The README says this module supports version 0.10.  Any plans to support 0.11?  Any known issues with attempting to use this with 0.11?

Thanks!

**Comment by leedm777** [comment]
I haven't done thorough testing, but I've run it a few times and it seems to work.

For better Sails v0.11 support, I'd like to use the new hook API, like I've done with [sails-hook-bunyan](https://github.com/building5/sails-hook-bunyan). But I haven't dug into it to see if they expose hooks for grunt tasks.

Please try on v0.11 and let me know if you run into any issues. Or let me know if it works perfectly, and I'll update the README.

Thanks!
