### ISSUE TITLE
remove the peerdependencies requirement

### ISSUE THREAD

**Issue by tjwebb** [building5/sails-db-migrate#19]
your `peerDependencies` screws up the latest version of sails that's about to be released. also, npm is phasing out that feature anyway.

**Comment by leedm777** [comment]
I don't think `peerDependencies` is going anywhere soon; they just changed the behavior of what it does when the peer is missing in npm@3.

Fixed in v1.2.0, but I haven't tested with latest sails yet. Let me know if there are any issues.

**Comment by tjwebb** [comment]
> I don't think peerDependencies is going anywhere soon; they just changed the behavior of what it does when the peer is missing in npm@3.

They are slowly phasing it out, just FYI. See this discussion for more info: https://github.com/npm/npm/issues/5080#issuecomment-40545599

Thanks for publishing the update.
