### ISSUE TITLE
Adding environment options

### ISSUE THREAD

**Issue by toptierlabs** [building5/sails-db-migrate#20]
It would be great if one could set the environment in which to run the migrations.
For example in rails, one has to do: 
rake db:migrate RAILS_ENV=testing

so it would be cool to add this to sails-db-migrate.

grunt db:migrate SAILS_ENV=testing

What do you think?

**Comment by leedm777** [comment]
This is already supported using the NODE_ENV environment variable.

    $ NODE_ENV=testing grunt db:migrate:up

Does that work for you?
