### ISSUE TITLE
Add db:seed task for fill db by data

### ISSUE THREAD

**Issue by Seafnox** [building5/sails-db-migrate#22]
In addition to updating the table schema, you need to fill them with data. For this there must be a separate grunt task. In the task, you can specify the source file that will contain code to generate the data (by use modules which the developer wants)

**Comment by leedm777** [comment]
A good idea, but the underlying [db-migrate seeder functionality](http://umigrate.readthedocs.org/projects/db-migrate/en/v0.10.x/Getting%20Started/usage/#seeder-introduction) doesn't distinguish between seeds and migrations.

This feels like something that would be its own `sails-db-seed` module. I don't have a need for one, so I don't think I'll write one anytime soon.

If you write one I will be glad to link to it from the `sails-db-migrate` README.

Thanks for the feedback!
