### ISSUE TITLE
sails.lift

### ISSUE THREAD

**Issue by avenger-teamave** [building5/sails-db-migrate#25]
sails.lift dont wont to start with port "-1"
> Fatal error: "port" argument must be >= 0 and < 65536

Can you change it with sails.load, so it is dont run http server?

**Comment by leedm777** [comment]
It might be a while before I can get around to fixing that. I'll gladly accept a PR, if you can do it.

**Comment by avenger-teamave** [comment]
I am push a request. Can You accept it?

**Comment by leedm777** [comment]
Merged, and published in v1.3.2.
