### ISSUE TITLE
grunt process does not terminate

### ISSUE THREAD

**Issue by xenyou** [building5/sails-db-migrate#31]
grunt process often remains after this.

```
grunt db:migrate:create --name add-some-fooz
```

**Comment by xenyou** [comment]
here is environments

```
$ grunt -v
grunt-cli: The grunt command line interface (v1.2.0)

sails-db-migrate@1.4.0
```

**Comment by leedm777** [comment]
@xenyou - What versions of Node.js and Sails are you using?

**Comment by kikuchi-facepeer** [comment]
node v0.10.4x
sails 0.11.x, 0.12.4

**Comment by xenyou** [comment]
node.js 0.11.4x
sails 0.11.x, 0.12.4

**Comment by leedm777** [comment]
I'm afraid I won't be of much help. I wrote the module for Sails 0.10 on Node.js 0.10; both of which are now very old and past End Of Life. I'll happily accept a good patch that fixes the issue, but I'm not going to be able to work on it myself.

**Comment by xenyou** [comment]
Oops, my node.js was 0.10.4x . 
I also tried this with sails 0.10.5. But it also caused.
