### ISSUE TITLE
Create migrations from file other then connections.js

### ISSUE THREAD

**Issue by quintenrosseel** [building5/sails-db-migrate#33]
HI guys, first of all a big cheers for this package that makes migrations a lot easier! 

Is there a way to specify that connections are defined in a file other then 'connections.js'? 
I define them in /env/production.js and /env/development.js. 
Haven't found any related questions on SO or in the documentation. 

Thanks! 

```
Running "db:migrate:create" (db:migrate) task
+ db-migrate create addSubscriberTable
Fatal error: could not find connection ProdPostgresql in ./config/connections.js
```

**Comment by leedm777** [comment]
> Is there a way to specify that connections are defined in a file other then 'connections.js'?

Sure. The error message you are seeing is referring to the standard way Sails.js is configured. But the way it's actually implemented, the connection could be in and file in the `./config` directory, as long as Sails loads it as a part of the `sails.config.connections` object.

Does that help?
